from reportlab.lib.pagesizes import letter
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import inch
from reportlab.platypus import SimpleDocTemplate, Paragraph, Table, TableStyle, Spacer, HRFlowable, PageBreak
from reportlab.lib import colors
from datetime import datetime
from typing import List
import os

def generate_receipt_pdf(transaction_data: dict, output_path: str) -> str:
    os.makedirs(os.path.dirname(output_path), exist_ok=True)
    doc = SimpleDocTemplate(output_path, pagesize=letter, leftMargin=0.75*inch, rightMargin=0.75*inch)
    styles = getSampleStyleSheet()
    elements = []

    title_style = ParagraphStyle("Title", parent=styles["Title"], fontSize=22, textColor=colors.HexColor("#1a1a2e"), spaceAfter=4)
    elements.append(Paragraph("BizTrack Receipts", title_style))
    elements.append(Paragraph("Transaction Receipt", styles["Heading2"]))
    elements.append(HRFlowable(width="100%", thickness=1, color=colors.HexColor("#1a1a2e")))
    elements.append(Spacer(1, 0.2 * inch))

    data = [
        ["Field", "Value"],
        ["Date", str(transaction_data.get("date", ""))],
        ["Description", str(transaction_data.get("name", ""))],
        ["Type", str(transaction_data.get("transaction_type", "")).upper()],
        ["Amount", f"${abs(transaction_data.get('amount', 0)):.2f}"],
        ["Category", str(transaction_data.get("category", "Uncategorized"))],
    ]

    if transaction_data.get("is_zelle"):
        data.append(["Zelle Direction", str(transaction_data.get("zelle_direction", "")).capitalize()])
        if transaction_data.get("zelle_counterparty"):
            data.append(["Zelle Party", str(transaction_data.get("zelle_counterparty", ""))])

    table = Table(data, colWidths=[2.5 * inch, 4.5 * inch])
    table.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#1a1a2e")),
        ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
        ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
        ("ROWBACKGROUNDS", (0, 1), (-1, -1), [colors.whitesmoke, colors.white]),
        ("GRID", (0, 0), (-1, -1), 0.5, colors.grey),
        ("FONTSIZE", (0, 0), (-1, -1), 10),
        ("PADDING", (0, 0), (-1, -1), 8),
    ]))
    elements.append(table)
    elements.append(Spacer(1, 0.4 * inch))
    elements.append(Paragraph(
        f"Generated by BizTrack Receipts on {datetime.utcnow().strftime('%Y-%m-%d %H:%M UTC')}",
        styles["Italic"]
    ))
    doc.build(elements)
    return output_path

def generate_batch_receipt_pdf(transactions: List[dict], totals: dict, output_path: str, period_label: str = "") -> str:
    os.makedirs(os.path.dirname(output_path), exist_ok=True)
    doc = SimpleDocTemplate(output_path, pagesize=letter, leftMargin=0.75*inch, rightMargin=0.75*inch)
    styles = getSampleStyleSheet()
    elements = []

    elements.append(Paragraph("BizTrack Receipts", styles["Title"]))
    elements.append(Paragraph(f"Transaction Summary {period_label}", styles["Heading2"]))
    elements.append(HRFlowable(width="100%", thickness=1, color=colors.HexColor("#1a1a2e")))
    elements.append(Spacer(1, 0.2 * inch))

    summary_data = [
        ["Metric", "Amount"],
        ["Total Deposits", f"${totals.get('total_deposits', 0):.2f}"],
        ["Total Withdrawals", f"${totals.get('total_withdrawals', 0):.2f}"],
        ["Zelle Sent", f"${totals.get('zelle_sent', 0):.2f}"],
        ["Zelle Received", f"${totals.get('zelle_received', 0):.2f}"],
        ["Net Balance", f"${totals.get('net_balance', 0):.2f}"],
    ]
    summary_table = Table(summary_data, colWidths=[3 * inch, 3 * inch])
    summary_table.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#16213e")),
        ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
        ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
        ("ROWBACKGROUNDS", (0, 1), (-1, -1), [colors.lightyellow, colors.white]),
        ("GRID", (0, 0), (-1, -1), 0.5, colors.grey),
        ("PADDING", (0, 0), (-1, -1), 8),
    ]))
    elements.append(summary_table)
    elements.append(Spacer(1, 0.4 * inch))
    elements.append(Paragraph("All Transactions", styles["Heading3"]))

    tx_data = [["Date", "Description", "Type", "Zelle", "Amount", "Category"]]
    for tx in transactions:
        tx_data.append([
            str(tx.get("date", ""))[:10],
            str(tx.get("name") or "")[:35],
            str(tx.get("transaction_type", "")).upper(),
            "Yes" if tx.get("is_zelle") else "No",
            f"${abs(tx.get('amount', 0)):.2f}",
            str(tx.get("category", ""))[:20],
        ])

    tx_table = Table(tx_data, colWidths=[1*inch, 2.2*inch, 0.8*inch, 0.6*inch, 0.9*inch, 1*inch])
    tx_table.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#0f3460")),
        ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
        ("FONTSIZE", (0, 0), (-1, -1), 8),
        ("ROWBACKGROUNDS", (0, 1), (-1, -1), [colors.white, colors.lightgrey]),
        ("GRID", (0, 0), (-1, -1), 0.3, colors.grey),
        ("PADDING", (0, 0), (-1, -1), 4),
    ]))
    elements.append(tx_table)
    elements.append(Spacer(1, 0.3 * inch))
    elements.append(Paragraph(
        f"Generated by BizTrack Receipts on {datetime.utcnow().strftime('%Y-%m-%d %H:%M UTC')}",
        styles["Italic"]
    ))
    doc.build(elements)
    return output_path


# --- Profit & Loss statement ---

NAVY = colors.HexColor("#1a1a2e")
SLATE = colors.HexColor("#16213e")
STEEL = colors.HexColor("#0f3460")
PROFIT_GREEN = colors.HexColor("#0b6b3a")
LOSS_RED = colors.HexColor("#a11616")


def _money(value: float) -> str:
    """Accounting format: negatives in parentheses, not with a minus sign."""
    if value < 0:
        return f"(${abs(value):,.2f})"
    return f"${value:,.2f}"


def _month_label(key: str, multi_year: bool) -> str:
    dt = datetime.strptime(key, "%Y-%m")
    return dt.strftime("%b %y") if multi_year else dt.strftime("%b")


def _chunk(items: List, size: int) -> List[List]:
    return [items[i:i + size] for i in range(0, len(items), size)]


def generate_pnl_pdf(pnl: dict, output_path: str, org_name: str = "") -> str:
    """Render a cash-basis P&L: summary page, then monthly breakdown pages."""
    os.makedirs(os.path.dirname(output_path), exist_ok=True)
    doc = SimpleDocTemplate(
        output_path,
        pagesize=letter,
        leftMargin=0.75 * inch,
        rightMargin=0.75 * inch,
        topMargin=0.7 * inch,
        bottomMargin=0.7 * inch,
        title="Profit & Loss Statement",
    )
    styles = getSampleStyleSheet()
    elements = []

    start = pnl["period_start"]
    end = pnl["period_end"]
    period_label = f"{start.strftime('%B %d, %Y')} — {end.strftime('%B %d, %Y')}"

    title_style = ParagraphStyle(
        "PnlTitle", parent=styles["Title"], fontSize=22, textColor=NAVY, spaceAfter=2
    )
    elements.append(Paragraph(org_name or "Clerq", title_style))
    elements.append(Paragraph("Profit &amp; Loss Statement", styles["Heading2"]))
    elements.append(Paragraph(period_label, styles["Normal"]))
    if pnl.get("basis") == "accrual-adjusted":
        basis_note = (
            "<i>Cash basis, adjusted for revenue paid in arrears — the payroll deposit "
            "that arrives on the 15th is booked to the month it was earned.</i>"
        )
    else:
        basis_note = "<i>Cash basis — recognized when funds moved, not when invoiced.</i>"
    elements.append(Paragraph(basis_note, styles["Normal"]))
    elements.append(HRFlowable(width="100%", thickness=1, color=NAVY))
    elements.append(Spacer(1, 0.25 * inch))

    # --- Summary statement ---
    rows = [["", "Amount"]]
    styling = [
        ("BACKGROUND", (0, 0), (-1, 0), NAVY),
        ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
        ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
        ("ALIGN", (1, 0), (1, -1), "RIGHT"),
        ("FONTSIZE", (0, 0), (-1, -1), 10),
        ("PADDING", (0, 0), (-1, -1), 6),
        ("LINEBELOW", (0, 0), (-1, 0), 0.5, colors.grey),
    ]

    def section_header(text: str):
        rows.append([text, ""])
        i = len(rows) - 1
        styling.extend([
            ("BACKGROUND", (0, i), (-1, i), colors.HexColor("#e8eaf0")),
            ("FONTNAME", (0, i), (-1, i), "Helvetica-Bold"),
            ("TEXTCOLOR", (0, i), (-1, i), SLATE),
        ])

    def total_row(text: str, amount: float):
        rows.append([text, _money(amount)])
        i = len(rows) - 1
        styling.extend([
            ("FONTNAME", (0, i), (-1, i), "Helvetica-Bold"),
            ("LINEABOVE", (0, i), (-1, i), 0.75, colors.grey),
        ])

    section_header("REVENUE")
    for line in pnl["revenue_lines"]:
        mark = " *" if line.get("manual") else ""
        rows.append([f"    {line['label']}{mark}", _money(line["amount"])])
    if not pnl["revenue_lines"]:
        rows.append(["    No revenue recorded in this period", _money(0)])
    total_row("Total Revenue", pnl["total_revenue"])

    rows.append(["", ""])
    section_header("OPERATING EXPENSES")
    for line in pnl["expense_lines"]:
        mark = " *" if line.get("manual") else ""
        rows.append([f"    {line['label']}{mark}", _money(line["amount"])])
    if not pnl["expense_lines"]:
        rows.append(["    No expenses recorded in this period", _money(0)])
    total_row("Total Operating Expenses", pnl["total_expenses"])

    rows.append(["", ""])
    net = pnl["net_profit"]
    rows.append(["NET PROFIT" if net >= 0 else "NET LOSS", _money(net)])
    net_i = len(rows) - 1
    styling.extend([
        ("BACKGROUND", (0, net_i), (-1, net_i), SLATE),
        ("TEXTCOLOR", (0, net_i), (-1, net_i), colors.white),
        ("FONTNAME", (0, net_i), (-1, net_i), "Helvetica-Bold"),
        ("FONTSIZE", (0, net_i), (-1, net_i), 12),
        ("PADDING", (0, net_i), (-1, net_i), 9),
    ])

    table = Table(rows, colWidths=[4.6 * inch, 2.4 * inch])
    table.setStyle(TableStyle(styling))
    elements.append(table)
    elements.append(Spacer(1, 0.2 * inch))

    margin_note = f"Net margin: {pnl['margin_pct']}%" if pnl["total_revenue"] else "Net margin: n/a (no revenue)"
    footer_bits = [margin_note, f"{pnl['transaction_count']} transactions in period"]
    if pnl.get("manual_entry_count"):
        footer_bits.append(f"{pnl['manual_entry_count']} manual entries (*)")
    elements.append(Paragraph(" &nbsp;·&nbsp; ".join(footer_bits), styles["Normal"]))

    # Months with no bank activity almost always mean a statement was never
    # uploaded or failed to parse. Saying so beats presenting a false zero.
    empty = pnl.get("empty_months") or []
    if empty:
        multi_year_gap = len({m[:4] for m in empty}) > 1
        listed = ", ".join(_month_label(m, multi_year_gap) for m in empty)
        elements.append(Spacer(1, 0.12 * inch))
        elements.append(Paragraph(
            f'<font color="#a11616"><b>Incomplete data:</b> no transactions at all in '
            f'{listed}. These months are almost certainly missing statements rather than '
            f'months with no activity — the totals above understate the period.</font>',
            styles["Normal"],
        ))

    # --- Excluded items ---
    if pnl["excluded_lines"]:
        elements.append(Spacer(1, 0.3 * inch))
        elements.append(Paragraph("Excluded from P&amp;L", styles["Heading3"]))
        ex_rows = [["Category", "Amount"]]
        for line in pnl["excluded_lines"]:
            ex_rows.append([line["label"], _money(line["amount"])])
        ex_rows.append(["Total excluded", _money(pnl["total_excluded"])])
        ex_table = Table(ex_rows, colWidths=[4.6 * inch, 2.4 * inch])
        ex_table.setStyle(TableStyle([
            ("BACKGROUND", (0, 0), (-1, 0), STEEL),
            ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
            ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
            ("FONTNAME", (0, -1), (-1, -1), "Helvetica-Bold"),
            ("ALIGN", (1, 0), (1, -1), "RIGHT"),
            ("FONTSIZE", (0, 0), (-1, -1), 9),
            ("GRID", (0, 0), (-1, -1), 0.3, colors.grey),
            ("PADDING", (0, 0), (-1, -1), 5),
        ]))
        elements.append(ex_table)
        elements.append(Spacer(1, 0.1 * inch))
        elements.append(Paragraph(
            "<i>These are balance-sheet movements, not income or expense, so they sit outside "
            "the statement. Transfers are money between the owners' own accounts — booking a "
            "partner topping up the account as revenue would overstate income. The mortgage is "
            "an owner draw; the home-office cost appears instead as a manual rent line, and "
            "counting both would double-dip. Loan payments are principal; the interest portion "
            "is a genuine expense, but bank transaction data cannot separate it — ask your "
            "accountant to book that adjustment.</i>",
            styles["Normal"],
        ))

    # --- Monthly breakdown pages ---
    months = pnl["months"]
    if len(months) > 1:
        multi_year = len({m[:4] for m in months}) > 1
        for group in _chunk(months, 6):
            elements.append(PageBreak())
            elements.append(Paragraph("Monthly Breakdown", styles["Heading2"]))
            elements.append(Paragraph(
                f"{_month_label(group[0], multi_year)} – {_month_label(group[-1], multi_year)}",
                styles["Normal"],
            ))
            elements.append(HRFlowable(width="100%", thickness=1, color=NAVY))
            elements.append(Spacer(1, 0.15 * inch))
            elements.append(_monthly_table(pnl, group, multi_year))

    elements.append(Spacer(1, 0.35 * inch))
    elements.append(Paragraph(
        f"Generated by Clerq on {datetime.utcnow().strftime('%Y-%m-%d %H:%M UTC')}",
        styles["Italic"],
    ))

    doc.build(elements)
    return output_path


def _monthly_table(pnl: dict, group: List[str], multi_year: bool) -> Table:
    """Rows are P&L lines, columns are months in `group`, plus a trailing total.

    That trailing column totals only the months shown on this page. When the
    period is split across pages it is a subtotal — labelling it "Total" while
    showing the full-period figure next to six columns that sum to something
    else reads as an arithmetic mistake.
    """
    is_partial = len(group) < len(pnl["months"])
    header = [""] + [_month_label(m, multi_year) for m in group] + (
        ["Subtotal"] if is_partial else ["Total"]
    )
    rows = [header]
    styling = [
        ("BACKGROUND", (0, 0), (-1, 0), NAVY),
        ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
        ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
        ("ALIGN", (1, 0), (-1, -1), "RIGHT"),
        ("FONTSIZE", (0, 0), (-1, -1), 7.5),
        ("PADDING", (0, 0), (-1, -1), 4),
        ("GRID", (0, 0), (-1, -1), 0.25, colors.HexColor("#c8ccd8")),
    ]

    def add_section(title: str, lines: List[dict], total_label: str):
        rows.append([title] + [""] * (len(group) + 1))
        i = len(rows) - 1
        styling.extend([
            ("BACKGROUND", (0, i), (-1, i), colors.HexColor("#e8eaf0")),
            ("FONTNAME", (0, i), (-1, i), "Helvetica-Bold"),
            ("TEXTCOLOR", (0, i), (-1, i), SLATE),
        ])
        for line in lines:
            rows.append(
                [f"  {line['label']}"]
                + [_money(line["monthly"].get(m, 0.0)) for m in group]
                + [_money(sum(line["monthly"].get(m, 0.0) for m in group))]
            )
        rows.append(
            [total_label]
            + [_money(sum(l["monthly"].get(m, 0.0) for l in lines)) for m in group]
            + [_money(sum(l["monthly"].get(m, 0.0) for l in lines for m in group))]
        )
        t = len(rows) - 1
        styling.extend([
            ("FONTNAME", (0, t), (-1, t), "Helvetica-Bold"),
            ("LINEABOVE", (0, t), (-1, t), 0.6, colors.grey),
        ])

    add_section("REVENUE", pnl["revenue_lines"], "Total Revenue")
    add_section("OPERATING EXPENSES", pnl["expense_lines"], "Total Expenses")

    by_month = {m["month"]: m for m in pnl["monthly_summary"]}
    rows.append(
        ["NET"]
        + [_money(by_month.get(m, {}).get("net", 0.0)) for m in group]
        + [_money(sum(by_month.get(m, {}).get("net", 0.0) for m in group))]
    )
    n = len(rows) - 1
    styling.extend([
        ("BACKGROUND", (0, n), (-1, n), SLATE),
        ("TEXTCOLOR", (0, n), (-1, n), colors.white),
        ("FONTNAME", (0, n), (-1, n), "Helvetica-Bold"),
        ("PADDING", (0, n), (-1, n), 6),
    ])

    label_w = 1.85 * inch
    num_w = (7.0 * inch - label_w) / (len(group) + 1)
    table = Table(rows, colWidths=[label_w] + [num_w] * (len(group) + 1), repeatRows=1)
    table.setStyle(TableStyle(styling))
    return table
