from reportlab.lib.pagesizes import letter
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import inch
from reportlab.platypus import SimpleDocTemplate, Paragraph, Table, TableStyle, Spacer, HRFlowable
from reportlab.lib import colors
from datetime import datetime
from typing import List
import os

def generate_receipt_pdf(transaction_data: dict, output_path: str) -> str:
    os.makedirs(os.path.dirname(output_path), exist_ok=True)
    doc = SimpleDocTemplate(output_path, pagesize=letter, leftMargin=0.75*inch, rightMargin=0.75*inch)
    styles = getSampleStyleSheet()
    elements = []

    title_style = ParagraphStyle("Title", parent=styles["Title"], fontSize=22, textColor=colors.HexColor("#1a1a2e"), spaceAfter=4)
    elements.append(Paragraph("BizTrack Receipts", title_style))
    elements.append(Paragraph("Transaction Receipt", styles["Heading2"]))
    elements.append(HRFlowable(width="100%", thickness=1, color=colors.HexColor("#1a1a2e")))
    elements.append(Spacer(1, 0.2 * inch))

    data = [
        ["Field", "Value"],
        ["Date", str(transaction_data.get("date", ""))],
        ["Description", str(transaction_data.get("name", ""))],
        ["Type", str(transaction_data.get("transaction_type", "")).upper()],
        ["Amount", f"${abs(transaction_data.get('amount', 0)):.2f}"],
        ["Category", str(transaction_data.get("category", "Uncategorized"))],
    ]

    if transaction_data.get("is_zelle"):
        data.append(["Zelle Direction", str(transaction_data.get("zelle_direction", "")).capitalize()])
        if transaction_data.get("zelle_counterparty"):
            data.append(["Zelle Party", str(transaction_data.get("zelle_counterparty", ""))])

    table = Table(data, colWidths=[2.5 * inch, 4.5 * inch])
    table.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#1a1a2e")),
        ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
        ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
        ("ROWBACKGROUNDS", (0, 1), (-1, -1), [colors.whitesmoke, colors.white]),
        ("GRID", (0, 0), (-1, -1), 0.5, colors.grey),
        ("FONTSIZE", (0, 0), (-1, -1), 10),
        ("PADDING", (0, 0), (-1, -1), 8),
    ]))
    elements.append(table)
    elements.append(Spacer(1, 0.4 * inch))
    elements.append(Paragraph(
        f"Generated by BizTrack Receipts on {datetime.utcnow().strftime('%Y-%m-%d %H:%M UTC')}",
        styles["Italic"]
    ))
    doc.build(elements)
    return output_path

def generate_batch_receipt_pdf(transactions: List[dict], totals: dict, output_path: str, period_label: str = "") -> str:
    os.makedirs(os.path.dirname(output_path), exist_ok=True)
    doc = SimpleDocTemplate(output_path, pagesize=letter, leftMargin=0.75*inch, rightMargin=0.75*inch)
    styles = getSampleStyleSheet()
    elements = []

    elements.append(Paragraph("BizTrack Receipts", styles["Title"]))
    elements.append(Paragraph(f"Transaction Summary {period_label}", styles["Heading2"]))
    elements.append(HRFlowable(width="100%", thickness=1, color=colors.HexColor("#1a1a2e")))
    elements.append(Spacer(1, 0.2 * inch))

    summary_data = [
        ["Metric", "Amount"],
        ["Total Deposits", f"${totals.get('total_deposits', 0):.2f}"],
        ["Total Withdrawals", f"${totals.get('total_withdrawals', 0):.2f}"],
        ["Zelle Sent", f"${totals.get('zelle_sent', 0):.2f}"],
        ["Zelle Received", f"${totals.get('zelle_received', 0):.2f}"],
        ["Net Balance", f"${totals.get('net_balance', 0):.2f}"],
    ]
    summary_table = Table(summary_data, colWidths=[3 * inch, 3 * inch])
    summary_table.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#16213e")),
        ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
        ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
        ("ROWBACKGROUNDS", (0, 1), (-1, -1), [colors.lightyellow, colors.white]),
        ("GRID", (0, 0), (-1, -1), 0.5, colors.grey),
        ("PADDING", (0, 0), (-1, -1), 8),
    ]))
    elements.append(summary_table)
    elements.append(Spacer(1, 0.4 * inch))
    elements.append(Paragraph("All Transactions", styles["Heading3"]))

    tx_data = [["Date", "Description", "Type", "Zelle", "Amount", "Category"]]
    for tx in transactions:
        tx_data.append([
            str(tx.get("date", ""))[:10],
            str(tx.get("name") or "")[:35],
            str(tx.get("transaction_type", "")).upper(),
            "Yes" if tx.get("is_zelle") else "No",
            f"${abs(tx.get('amount', 0)):.2f}",
            str(tx.get("category", ""))[:20],
        ])

    tx_table = Table(tx_data, colWidths=[1*inch, 2.2*inch, 0.8*inch, 0.6*inch, 0.9*inch, 1*inch])
    tx_table.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#0f3460")),
        ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
        ("FONTSIZE", (0, 0), (-1, -1), 8),
        ("ROWBACKGROUNDS", (0, 1), (-1, -1), [colors.white, colors.lightgrey]),
        ("GRID", (0, 0), (-1, -1), 0.3, colors.grey),
        ("PADDING", (0, 0), (-1, -1), 4),
    ]))
    elements.append(tx_table)
    elements.append(Spacer(1, 0.3 * inch))
    elements.append(Paragraph(
        f"Generated by BizTrack Receipts on {datetime.utcnow().strftime('%Y-%m-%d %H:%M UTC')}",
        styles["Italic"]
    ))
    doc.build(elements)
    return output_path
